### ISSUE TITLE
Can u add UseKeychain support ?

### ISSUE THREAD

**Issue by hugomrdias** [rdp/homebrew-openssh-gssapi#1]
Please :)

**Comment by rdp** [comment]
Do you have a use case for this?  NB there is already `kinit --keychain` and apparently you can use `gpg-agent` as a workaround https://github.com/Homebrew/homebrew-dupes/pull/482#issuecomment-118994372 FWIW?  I also don't understand it fully... and it exposes passwords to the "visible terminal" apparently https://github.com/Homebrew/homebrew-dupes/issues/413 but I'll look into it :)

https://github.com/jirsbek/SSH-keys-in-macOS-Sierra-keychain may also be helpful. Also https://github.com/Homebrew/homebrew-dupes/issues/655

**Comment by rdp** [comment]
OK added

`brew install rdp/homebrew-openssh-gssapi/openssh-gssapi-hpn --with-gssapi-support --with-keychain-support `

**Comment by rdp** [comment]
I added it

On Friday, April 6, 2018, Hugo Dias <notifications@github.com> wrote:
> Please :)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/W5VN0Xjc8Ee7u9xaymq2s3UfNJojQJ0fHb8coEeP1gnkrvPrksT2xeHw7E3U7uJNP-yreOBGCwh_G3IiX9Mb9XE9bxLqDCy83QYxhOMvgxxVkVQGa5ijwWqMHA-16TgGahJmZMRCgjjeOlkLxBIY7evu4HF-vQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAw0OeBXLYIOFAk6NosMQUTJ7wvYH1Nks5tl4yugaJpZM4TKSPw.gif>

**Comment by rdp** [comment]
actually it's not UseKeyChain https://superuser.com/questions/1330469/macos-keychain-access-holds-on-to-ssh-passphrase-indefinitely but is it similar? LOL  I don't know where the patch for UseKeyChain can be found...

**Comment by Tabiskabis** [comment]
There is no single ready patch. You'd probably have to diff it from [Apple's OpenSSH]( )https://github.com/search?q=repo%3Aapple-oss-distributions%2FOpenSSH+usekeychain&type=code). 
But going after that feature means going down a rabbit hole, I'm afraid.

To work with keychain's access-group "com.apple.ssh.passphrases", the code would need to be built with [the corresponding entitlement](https://github.com/apple-opensource/OpenSSH/blob/master/Entitlements/ssh.entitlements). Which in turn depend on code notarization, if I understand correctly.
