### ISSUE TITLE
Download failed: https://opensource.apple.com/source/OpenSSH/OpenSSH-209.50.1/com.openssh.sshd.sb

### ISSUE THREAD

**Issue by BethLong06** [rdp/homebrew-openssh-gssapi#13]
I'm running MacOS Sonoma 14.5 with an M1 chip and I'm trying to get kerberos working (following the instructions [here](https://frankenthal.dev/post/ssh_kerberos_keytabs_macos/)) but when I do:
`brew install rdp/homebrew-openssh-gssapi/openssh-patched --with-gssapi-support`
I get:

```
==> Downloading https://opensource.apple.com/source/OpenSSH/OpenSSH-209.50.1/com.openssh.sshd.sb
curl: (22) The requested URL returned error: 404

Error: openssh-patched: Failed to download resource "openssh-patched--com.openssh.sshd.sb"
Download failed: https://opensource.apple.com/source/OpenSSH/OpenSSH-209.50.1/com.openssh.sshd.sb
```
I tried `brew tap rdp/homebrew-openssh-gssapi` which gives me no output, and then `brew install rdp/homebrew-openssh-gssapi/openssh-patched --with-gssapi-support` again but it still fails in the same place

**Comment by rdp** [comment]
I fixed this but I don't have a mac to actually get this tested...

**Comment by BethLong06** [comment]
I tried the command again and it installs without errors now. Thanks!

**Comment by BethLong06** [comment]
I tried the command again and it installs without errors now. Thanks!
