### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by qgadrian** [rdp/homebrew-openssh-gssapi#4]
I'm having a segmentation fault when trying to connect to a host.

The ssh config has enabled the GSSAPIAuthentication (without the config it works fine, but it is needed in order to connect to the host):

```
GSSAPIAuthentication yes
GSSAPIDelegateCredentials yes
GSSAPIKeyExchange yes
```

The verbose output of `ssh -vvvv thehost`, I cannot find more info about the segfault.

```
OpenSSH_7.6p1, OpenSSL 1.0.2q  20 Nov 2018
debug1: Reading configuration data /Users/qgadrian/.ssh/config
debug1: /Users/qgadrian/.ssh/config line 1: Applying options for *
debug1: /Users/qgadrian/.ssh/config line 17: Applying options for *.test?
debug1: Reading configuration data /opt/local/etc/ssh/ssh_config
debug2: resolving "thehost" port 22
debug2: ssh_connect_direct: needpriv 0
debug1: Connecting to thehost [*.*.*.*] port 22.
debug1: Connection established.
debug1: identity file /Users/qgadrian/.ssh/id_rsa type 0
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/qgadrian/.ssh/id_ed25519-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_7.6
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1
debug1: match: OpenSSH_6.6.1 pat OpenSSH_6.6.1* compat 0x04000000
debug2: fd 5 setting O_NONBLOCK
debug1: Authenticating to thehost:22 as 'root'
debug3: hostkeys_foreach: reading file "/Users/qgadrian/.ssh/known_hosts"
debug3: record_hostkey: found key type ECDSA in file /Users/qgadrian/.ssh/known_hosts:17
debug3: load_hostkeys: loaded 1 keys from thehost
debug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
[1]    25564 segmentation fault  ssh -vvvv thehost
```

OS info

```
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54
```

Tried & info:
* The usual reboot, reinstall openssl, kerberos... 
* `brew doctor` shows no problem

Does anyone have idea what might be the problem?

**Comment by rdp** [comment]
Nothing off hand, how did you install homebrew-openssh-gssapi ? Does normal
ssh work? I guess you could run it through gdb but that sounds
painful...maybe try on an older version of openssh but that also sounds
painful..

**Comment by qgadrian** [comment]
Yeah I know... 

I installed with the gssapiauthentication support, as the README says.

Everything was working fine until two days ago, so the initial installation was successful. `ssh` works fine by itself, I can connect to other hosts without issues. I don’t know if it was since last OSX update, because the only changes I made in my system was that and installing a `vim` plugin (`youcompleteme`, which plays with c files) so I don’t know who to blame (╯°□°）╯︵ ┻━┻ 

I will reinstall the system since it will be less effort than using gdb and I do need to make ssh work. It’s not ideal and feels bad, but ¯\_(ツ)_/¯

**Comment by rdp** [comment]
maybe remove and reinstall all homebrew files help?

**Comment by qgadrian** [comment]
I did. Also tried the MacPorts patch (not sure if it’s same or not) but nothing worked so far.

**Comment by qgadrian** [comment]
BTW I just have a clean install and I'm still getting the segfault 😱

Will come back with more details if can get them...

**Comment by qgadrian** [comment]
BTW I just have a clean install and I'm still getting the segfault 😱

Using `lldb` works fine, I cannot get the segfault 🤔

```
lldb ssh thehost
(lldb) target create "ssh"
Current executable set to 'ssh' (x86_64).
(lldb) settings set -- target.run-args  "thehost"
(lldb) r
Process 1633 launched: '/usr/local/bin/ssh' (x86_64)
Last login: Wed Dec 19 07:58:50 2018 from thevpn
[root@thehost ~]#
```

**Comment by rdp** [comment]
Weird, wish I could repro it...PR's welcome!  What if you just build vanilla openssh it works?

**Comment by rdp** [comment]
If macports version also fails...I have really no idea, file a bug report with openssh maybe?  Good luck!
