### ISSUE TITLE
OpenSSL 1.1.0 not yet supported

### ISSUE THREAD

**Issue by gmonaie** [rdp/homebrew-openssh-gssapi#5]
after running:

`brew install rdp/homebrew-openssh-gssapi/openssh-patched --with-gssapi-support --with-hpn`

received this error during the installation:

```
checking OpenSSL header version... 1010104f (OpenSSL 1.1.1d  10 Sep 2019)
checking OpenSSL library version... configure: error: OpenSSL >= 1.1.0 is not yet supported (have "1010104f (OpenSSL 1.1.1d  10 Sep 2019)")
```

**Comment by rdp** [comment]
sure enough, brew doesn't even have OpenSSL 1.0 anymore.  OK attempted to update it, though it broke a few patch options sadly...

**Comment by rdp** [comment]
Seems to build OK now...
